// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Import both the Sidebar and Navbar components
import Sidebar from "@/components/Sidebar"; // Adjust path if needed
import Navbar from "@/components/Navbar"; // Adjust path if needed

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        {" "}
        {/* Optional: Add a light background color to the body */}
        <div className="flex">
          {/* The Sidebar is fixed on mobile and relative on desktop */}
          <Sidebar />

          {/* This div wraps the main content area (Navbar + Page Content) */}
          <div className="flex flex-col flex-1 md:ml-64">
            {/* The Navbar sits at the top of the main content area */}
            <Navbar />

            {/* The actual page content will be rendered here */}
            <main className="p-4 md:p-8">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
